version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-database
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./resources:/app/resources
      - ./vectorstore:/app/vectorstore  # ⬅️ Montaje persistente
    restart: unless-stopped
